name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 프로젝트 체크아웃
      - uses: actions/checkout@v3

      # 2. Java 환경 설정
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'  # Java 배포판: Corretto
          java-version: '17'        # Java 버전: 17

      # 3. Gradle 캐시 설정
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle 실행 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. Gradle 빌드 실행
      - name: Build with Gradle
        run: ./gradlew clean build -Dspring.profiles.active=test